sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t guk0/docker-react-app -f Dockerfile .

script:
  - docker run -e CI=true guk0/docker-react-app npm run test -- --coverage

deploy: 
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-957930470982"
  bucket_path: "docker-react-app"
  on: 
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  access_secret_key: $AWS_SECRET_ACCESS_KEY
